id: P007135
initial_creation_type: ocr
source_metadata:
  id: bdr:W30292
  title: བཀྲ་ཤིས་ཚེ་རིང་མའི་སྒྲུབ་སྐོར་སོགས
  author: ''
  volumes:
    3b90b46fa8d544da81cd39e1cffdd29e:
      image_group_id: I6040
      title: ''
      volume_number: 1
      total_pages: 584
ebook_metadata:
  title: བཀྲ་ཤིས་ཚེ་རིང་མའི་སྒྲུབ་སྐོར་སོགས
  author: ''
  sku: P007135
  cover: cover.jpg
  layers:
  - pagination
