id: P007135
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-17 12:43:58.901601
source_metadata:
  id: bdr:W30292
  title: བཀྲ་ཤིས་ཚེ་རིང་མའི་སྒྲུབ་སྐོར་སོགས
  author: ''
  volumes:
    3b90b46fa8d544da81cd39e1cffdd29e:
      image_group_id: I6040
      title: ''
      volume_number: 1
      total_pages: 584
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
