id: I5097CC5F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T00:50:46+00:00'
last_modified: '2022-06-09T06:22:13.997500+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30292
  title: བཀྲ་ཤིས་ཚེ་རིང་མའི་སྒྲུབ་སྐོར་སོགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    822B:
      image_group_id: I6040
      title: ''
      total_pages: 584
      order: 1
      base_file: 822B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
